name: 游리 Pacman Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los d칤as a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install git+https://github.com/platane/pacman-contribution-graph

      - name: Generar gr치fico Pacman
        run: |
          pacman-graph --user Sandrez12 --output output/pacman-contribution-graph.svg

      - name: Commit y Push si hay cambios
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add output/pacman-contribution-graph.svg
          git commit -m "游리 Actualizar gr치fico Pacman" || echo "Sin cambios"
          git push
