name: 游리 Pacman Contributions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Generar gr치fico Pacman con Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/output ghcr.io/platane/pacman-contribution-graph \
            --user Sandrez12 \
            --output /output/output/pacman-contribution-graph.svg

      - name: Commit y push si hay cambios
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add output/pacman-contribution-graph.svg
          git commit -m "游리 Actualizar gr치fico Pacman" || echo "Sin cambios"
          git push
